name: Run monitor_stock.py every day

on:
  schedule:
    - cron: '50 6 * * *'  # 매일 06:50 KST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul   # 한국 시간대 적용
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y fonts-nanum fonts-noto-cjk

      - name: Run monitor_stock.py
        run: python monitor_stock.py
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
